services:
  - type: web
    name: aqi-prediction-flask
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --preload --workers 3 --bind 0.0.0.0:$PORT
    envVars:
      - key: WAQI_TOKEN
        # leave blank in repo; set this on Render dashboard instead
        value: "49979a07221b1ab6781c500a5eaa6e1de513d476"
      - key: MODEL_PATH
        value: new_model_realtime.pickle
