services:
  - type: web
    name: aqi-prediction-flask
    env: python
    plan: free
    region: oregon

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --preload --workers 3 --bind 0.0.0.0:$PORT

    envVars:
      - key: WAQI_TOKEN
        value: ""   # Set actual token in Render dashboard
      - key: MODEL_PATH
        value: new_model_realtime.pickle
